CREATE TABLE `football_match`(
  id        INT  NOT NULL AUTO_INCREMENT
  ,date     date  NOT NULL
  ,home_team VARCHAR(20) NOT NULL
  ,away_team VARCHAR(20) NOT NULL
  ,home_goals     INTEGER  NOT NULL
  ,away_goals     INTEGER  NOT NULL
  ,match_result      VARCHAR(1) NOT NULL
  ,PRIMARY KEY(id)
);

INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/08/17','LEGANES','ALAVES',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/08/17','VALENCIA','LAS PALMAS',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/08/17','CELTA','SOCIEDAD',2,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/08/17','GIRONA','ATH MADRID',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/08/17','SEVILLA','ESPANOL',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/08/17','ATH BILBAO','GETAFE',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/08/17','BARCELONA','BETIS',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/08/17','LA CORUNA','REAL MADRID',0,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/08/17','LEVANTE','VILLARREAL',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/08/17','MALAGA','EIBAR',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('25/08/17','BETIS','CELTA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('25/08/17','SOCIEDAD','VILLARREAL',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('26/08/17','ALAVES','BARCELONA',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('26/08/17','GIRONA','MALAGA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('26/08/17','LAS PALMAS','ATH MADRID',1,5,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('26/08/17','LEVANTE','LA CORUNA',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('27/08/17','EIBAR','ATH BILBAO',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('27/08/17','ESPANOL','LEGANES',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('27/08/17','GETAFE','SEVILLA',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('27/08/17','REAL MADRID','VALENCIA',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('08/09/17','LEGANES','GETAFE',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('09/09/17','BARCELONA','ESPANOL',5,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('09/09/17','REAL MADRID','LEVANTE',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('09/09/17','SEVILLA','EIBAR',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('09/09/17','VALENCIA','ATH MADRID',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/09/17','ATH BILBAO','GIRONA',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/09/17','CELTA','ALAVES',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/09/17','LA CORUNA','SOCIEDAD',2,4,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/09/17','VILLARREAL','BETIS',3,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('11/09/17','MALAGA','LAS PALMAS',1,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('15/09/17','EIBAR','LEGANES',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('16/09/17','ATH MADRID','MALAGA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('16/09/17','BETIS','LA CORUNA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('16/09/17','GETAFE','BARCELONA',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('16/09/17','LEVANTE','VALENCIA',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/09/17','ALAVES','VILLARREAL',0,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/09/17','GIRONA','SEVILLA',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/09/17','LAS PALMAS','ATH BILBAO',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/09/17','SOCIEDAD','REAL MADRID',1,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/09/17','ESPANOL','CELTA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/09/17','BARCELONA','EIBAR',6,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/09/17','VALENCIA','MALAGA',5,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/09/17','ATH BILBAO','ATH MADRID',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/09/17','LA CORUNA','ALAVES',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/09/17','LEGANES','GIRONA',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/09/17','REAL MADRID','BETIS',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/09/17','SEVILLA','LAS PALMAS',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/09/17','CELTA','GETAFE',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/09/17','LEVANTE','SOCIEDAD',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/09/17','VILLARREAL','ESPANOL',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('23/09/17','ALAVES','REAL MADRID',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('23/09/17','ATH MADRID','SEVILLA',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('23/09/17','GIRONA','BARCELONA',0,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('23/09/17','MALAGA','ATH BILBAO',3,3,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('24/09/17','EIBAR','CELTA',0,4,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('24/09/17','ESPANOL','LA CORUNA',4,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('24/09/17','GETAFE','VILLARREAL',4,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('24/09/17','LAS PALMAS','LEGANES',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('24/09/17','SOCIEDAD','VALENCIA',2,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('25/09/17','BETIS','LEVANTE',4,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('29/09/17','CELTA','GIRONA',3,3,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('30/09/17','LA CORUNA','GETAFE',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('30/09/17','LEGANES','ATH MADRID',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('30/09/17','LEVANTE','ALAVES',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('30/09/17','SEVILLA','MALAGA',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/10/17','BARCELONA','LAS PALMAS',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/10/17','REAL MADRID','ESPANOL',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/10/17','SOCIEDAD','BETIS',4,4,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/10/17','VALENCIA','ATH BILBAO',3,2,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/10/17','VILLARREAL','EIBAR',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('13/10/17','ESPANOL','LEVANTE',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('14/10/17','ALAVES','SOCIEDAD',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('14/10/17','ATH BILBAO','SEVILLA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('14/10/17','ATH MADRID','BARCELONA',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('14/10/17','GETAFE','REAL MADRID',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('15/10/17','BETIS','VALENCIA',3,6,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('15/10/17','EIBAR','LA CORUNA',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('15/10/17','GIRONA','VILLARREAL',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('15/10/17','MALAGA','LEGANES',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('16/10/17','LAS PALMAS','CELTA',2,5,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/10/17','BARCELONA','MALAGA',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/10/17','BETIS','ALAVES',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/10/17','LEVANTE','GETAFE',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/10/17','VALENCIA','SEVILLA',4,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('22/10/17','CELTA','ATH MADRID',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('22/10/17','LEGANES','ATH BILBAO',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('22/10/17','REAL MADRID','EIBAR',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('22/10/17','VILLARREAL','LAS PALMAS',4,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('23/10/17','LA CORUNA','GIRONA',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('23/10/17','SOCIEDAD','ESPANOL',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/10/17','ALAVES','VALENCIA',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/10/17','ATH BILBAO','BARCELONA',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/10/17','ATH MADRID','VILLARREAL',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/10/17','SEVILLA','LEGANES',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('29/10/17','EIBAR','LEVANTE',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('29/10/17','GETAFE','SOCIEDAD',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('29/10/17','GIRONA','REAL MADRID',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('29/10/17','MALAGA','CELTA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('30/10/17','ESPANOL','BETIS',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('30/10/17','LAS PALMAS','LA CORUNA',1,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/11/17','BETIS','GETAFE',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/11/17','ALAVES','ESPANOL',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/11/17','BARCELONA','SEVILLA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/11/17','LA CORUNA','ATH MADRID',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/11/17','VALENCIA','LEGANES',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('05/11/17','CELTA','ATH BILBAO',3,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('05/11/17','LEVANTE','GIRONA',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('05/11/17','REAL MADRID','LAS PALMAS',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('05/11/17','SOCIEDAD','EIBAR',3,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('05/11/17','VILLARREAL','MALAGA',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/11/17','GIRONA','SOCIEDAD',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/11/17','ATH MADRID','REAL MADRID',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/11/17','GETAFE','ALAVES',4,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/11/17','LEGANES','BARCELONA',0,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/11/17','SEVILLA','CELTA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/11/17','ATH BILBAO','VILLARREAL',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/11/17','ESPANOL','VALENCIA',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/11/17','LAS PALMAS','LEVANTE',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/11/17','MALAGA','LA CORUNA',3,2,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/11/17','EIBAR','BETIS',5,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('24/11/17','CELTA','LEGANES',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('25/11/17','ALAVES','EIBAR',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('25/11/17','BETIS','GIRONA',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('25/11/17','LEVANTE','ATH MADRID',0,5,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('25/11/17','REAL MADRID','MALAGA',3,2,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('26/11/17','LA CORUNA','ATH BILBAO',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('26/11/17','SOCIEDAD','LAS PALMAS',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('26/11/17','VALENCIA','BARCELONA',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('26/11/17','VILLARREAL','SEVILLA',2,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('27/11/17','ESPANOL','GETAFE',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/12/17','MALAGA','LEVANTE',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('02/12/17','ATH BILBAO','REAL MADRID',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('02/12/17','ATH MADRID','SOCIEDAD',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('02/12/17','BARCELONA','CELTA',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('02/12/17','SEVILLA','LA CORUNA',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/12/17','EIBAR','ESPANOL',3,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/12/17','GETAFE','VALENCIA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/12/17','LAS PALMAS','BETIS',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/12/17','LEGANES','VILLARREAL',3,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/12/17','GIRONA','ALAVES',2,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('08/12/17','ALAVES','LAS PALMAS',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('09/12/17','GETAFE','EIBAR',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('09/12/17','LA CORUNA','LEGANES',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('09/12/17','REAL MADRID','SEVILLA',5,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('09/12/17','VALENCIA','CELTA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/12/17','BETIS','ATH MADRID',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/12/17','LEVANTE','ATH BILBAO',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/12/17','SOCIEDAD','MALAGA',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/12/17','VILLARREAL','BARCELONA',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('11/12/17','ESPANOL','GIRONA',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('15/12/17','SEVILLA','LEVANTE',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('16/12/17','ATH BILBAO','SOCIEDAD',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('16/12/17','ATH MADRID','ALAVES',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('16/12/17','EIBAR','VALENCIA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/12/17','BARCELONA','LA CORUNA',4,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/12/17','CELTA','VILLARREAL',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/12/17','GIRONA','GETAFE',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/12/17','LAS PALMAS','ESPANOL',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/12/17','MALAGA','BETIS',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/12/17','LEVANTE','LEGANES',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/12/17','GETAFE','LAS PALMAS',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/12/17','SOCIEDAD','SEVILLA',3,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/12/17','ALAVES','MALAGA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/12/17','EIBAR','GIRONA',4,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('22/12/17','BETIS','ATH BILBAO',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('22/12/17','ESPANOL','ATH MADRID',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('23/12/17','LA CORUNA','CELTA',1,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('23/12/17','REAL MADRID','BARCELONA',0,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('23/12/17','VALENCIA','VILLARREAL',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('06/01/18','ATH MADRID','GETAFE',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('06/01/18','LAS PALMAS','EIBAR',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('06/01/18','SEVILLA','BETIS',3,5,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('06/01/18','VALENCIA','GIRONA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('07/01/18','ATH BILBAO','ALAVES',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('07/01/18','BARCELONA','LEVANTE',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('07/01/18','CELTA','REAL MADRID',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('07/01/18','LEGANES','SOCIEDAD',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('07/01/18','VILLARREAL','LA CORUNA',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('08/01/18','MALAGA','ESPANOL',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('12/01/18','GETAFE','MALAGA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('13/01/18','EIBAR','ATH MADRID',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('13/01/18','GIRONA','LAS PALMAS',6,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('13/01/18','LA CORUNA','VALENCIA',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('13/01/18','REAL MADRID','VILLARREAL',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('14/01/18','ALAVES','SEVILLA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('14/01/18','ESPANOL','ATH BILBAO',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('14/01/18','LEVANTE','CELTA',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('14/01/18','SOCIEDAD','BARCELONA',2,4,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('15/01/18','BETIS','LEGANES',3,2,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/01/18','GETAFE','ATH BILBAO',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/01/18','ATH MADRID','GIRONA',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/01/18','ESPANOL','SEVILLA',0,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/01/18','LAS PALMAS','VALENCIA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('20/01/18','VILLARREAL','LEVANTE',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/01/18','ALAVES','LEGANES',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/01/18','BETIS','BARCELONA',0,5,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/01/18','REAL MADRID','LA CORUNA',7,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/01/18','SOCIEDAD','CELTA',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('22/01/18','EIBAR','MALAGA',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('26/01/18','ATH BILBAO','EIBAR',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('27/01/18','LA CORUNA','LEVANTE',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('27/01/18','MALAGA','GIRONA',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('27/01/18','VALENCIA','REAL MADRID',1,4,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('27/01/18','VILLARREAL','SOCIEDAD',4,2,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/01/18','ATH MADRID','LAS PALMAS',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/01/18','BARCELONA','ALAVES',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/01/18','LEGANES','ESPANOL',3,2,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/01/18','SEVILLA','GETAFE',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('29/01/18','CELTA','BETIS',3,2,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('02/02/18','SOCIEDAD','LA CORUNA',5,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/02/18','ALAVES','CELTA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/02/18','BETIS','VILLARREAL',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/02/18','EIBAR','SEVILLA',5,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/02/18','LEVANTE','REAL MADRID',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/02/18','ATH MADRID','VALENCIA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/02/18','ESPANOL','BARCELONA',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/02/18','GETAFE','LEGANES',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/02/18','GIRONA','ATH BILBAO',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('05/02/18','LAS PALMAS','MALAGA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('09/02/18','ATH BILBAO','LAS PALMAS',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/02/18','LEGANES','EIBAR',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/02/18','MALAGA','ATH MADRID',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/02/18','REAL MADRID','SOCIEDAD',5,2,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/02/18','VILLARREAL','ALAVES',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('11/02/18','BARCELONA','GETAFE',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('11/02/18','CELTA','ESPANOL',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('11/02/18','SEVILLA','GIRONA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('11/02/18','VALENCIA','LEVANTE',3,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('12/02/18','LA CORUNA','BETIS',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('16/02/18','GIRONA','LEGANES',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/02/18','ALAVES','LA CORUNA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/02/18','EIBAR','BARCELONA',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/02/18','LAS PALMAS','SEVILLA',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/02/18','MALAGA','VALENCIA',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/02/18','ATH MADRID','ATH BILBAO',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/02/18','BETIS','REAL MADRID',3,5,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/02/18','ESPANOL','VILLARREAL',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/02/18','SOCIEDAD','LEVANTE',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('19/02/18','GETAFE','CELTA',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('21/02/18','LEGANES','REAL MADRID',1,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('23/02/18','LA CORUNA','ESPANOL',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('24/02/18','BARCELONA','GIRONA',6,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('24/02/18','CELTA','EIBAR',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('24/02/18','LEGANES','LAS PALMAS',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('24/02/18','REAL MADRID','ALAVES',4,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('25/02/18','ATH BILBAO','MALAGA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('25/02/18','SEVILLA','ATH MADRID',2,5,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('25/02/18','VALENCIA','SOCIEDAD',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('25/02/18','VILLARREAL','GETAFE',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('26/02/18','LEVANTE','BETIS',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('27/02/18','ESPANOL','REAL MADRID',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('27/02/18','GIRONA','CELTA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/02/18','ATH BILBAO','VALENCIA',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/02/18','ATH MADRID','LEGANES',4,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/02/18','EIBAR','VILLARREAL',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/02/18','GETAFE','LA CORUNA',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('28/02/18','MALAGA','SEVILLA',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/03/18','ALAVES','LEVANTE',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/03/18','BETIS','SOCIEDAD',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/03/18','LAS PALMAS','BARCELONA',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/03/18','LA CORUNA','EIBAR',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/03/18','LEGANES','MALAGA',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/03/18','REAL MADRID','GETAFE',3,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/03/18','SEVILLA','ATH BILBAO',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('03/03/18','VILLARREAL','GIRONA',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/03/18','BARCELONA','ATH MADRID',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/03/18','LEVANTE','ESPANOL',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/03/18','SOCIEDAD','ALAVES',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('04/03/18','VALENCIA','BETIS',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('05/03/18','CELTA','LAS PALMAS',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('09/03/18','GIRONA','LA CORUNA',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/03/18','EIBAR','REAL MADRID',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/03/18','GETAFE','LEVANTE',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/03/18','MALAGA','BARCELONA',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('10/03/18','SEVILLA','VALENCIA',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('11/03/18','ATH BILBAO','LEGANES',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('11/03/18','ATH MADRID','CELTA',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('11/03/18','ESPANOL','SOCIEDAD',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('11/03/18','LAS PALMAS','VILLARREAL',0,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('12/03/18','ALAVES','BETIS',1,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('16/03/18','LEVANTE','EIBAR',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/03/18','BETIS','ESPANOL',3,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/03/18','LA CORUNA','LAS PALMAS',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/03/18','SOCIEDAD','GETAFE',1,2,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('17/03/18','VALENCIA','ALAVES',3,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/03/18','BARCELONA','ATH BILBAO',2,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/03/18','CELTA','MALAGA',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/03/18','LEGANES','SEVILLA',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/03/18','REAL MADRID','GIRONA',6,3,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('18/03/18','VILLARREAL','ATH MADRID',2,1,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('31/03/18','ATH BILBAO','CELTA',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('31/03/18','GIRONA','LEVANTE',1,1,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('31/03/18','LAS PALMAS','REAL MADRID',0,3,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('31/03/18','SEVILLA','BARCELONA',2,2,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/04/18','ATH MADRID','LA CORUNA',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/04/18','EIBAR','SOCIEDAD',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/04/18','ESPANOL','ALAVES',0,0,'D');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/04/18','LEGANES','VALENCIA',0,1,'A');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('01/04/18','MALAGA','VILLARREAL',1,0,'H');
INSERT INTO football_match(date,home_team,away_team,home_goals,away_goals,match_result) VALUES ('02/04/18','GETAFE','BETIS',0,1,'A');
